package org.incava.diffj.util;

public enum ChangeType {
	ACCESS_ADDED("ACCESS_ADDED"), ACCESS_CHANGED("ACCESS_CHANGED"), ACCESS_REMOVED(
			"ACCESS_REMOVED"), CODE_ADDED("CODE_ADDED"), CODE_CHANGED(
			"CODE_CHANGED"), CODE_REMOVED("CODE_REMOVED"), CONSTRUCTOR_ADDED(
			"CONSTRUCTOR_ADDED"), CONSTRUCTOR_REMOVED("CONSTRUCTOR_REMOVED"), EXTENDED_TYPE_ADDED(
			"EXTENDED_TYPE_ADDED"), EXTENDED_TYPE_CHANGED(
			"EXTENDED_TYPE_CHANGED"), EXTENDED_TYPE_REMOVED(
			"EXTENDED_TYPE_REMOVED"), FIELD_ADDED("FIELD_ADDED"), FIELD_REMOVED(
			"FIELD_REMOVED"), IMPLEMENTED_TYPE_ADDED("IMPLEMENTED_TYPE_ADDED"), IMPLEMENTED_TYPE_CHANGED(
			"IMPLEMENTED_TYPE_CHANGED"), IMPLEMENTED_TYPE_REMOVED(
			"IMPLEMENTED_TYPE_REMOVED"), IMPORT_ADDED("IMPORT_ADDED"), IMPORT_REMOVED(
			"IMPORT_REMOVED"), IMPORT_SECTION_ADDED("IMPORT_SECTION_ADDED"), IMPORT_SECTION_REMOVED(
			"IMPORT_SECTION_REMOVED"), INITIALIZER_ADDED("INITIALIZER_ADDED"), INITIALIZER_REMOVED(
			"INITIALIZER_REMOVED"), INNER_CLASS_ADDED("INNER_CLASS_ADDED"), INNER_CLASS_REMOVED(
			"INNER_CLASS_REMOVED"), INNER_INTERFACE_ADDED(
			"INNER_INTERFACE_ADDED"), INNER_INTERFACE_REMOVED(
			"INNER_INTERFACE_REMOVED"), METHOD_ADDED("METHOD_ADDED"), METHOD_BLOCK_ADDED(
			"METHOD_BLOCK_ADDED"), METHOD_BLOCK_REMOVED("METHOD_BLOCK_REMOVED"), METHOD_REMOVED(
			"METHOD_REMOVED"), MODIFIER_ADDED("MODIFIER_ADDED"), MODIFIER_CHANGED(
			"MODIFIER_CHANGED"), MODIFIER_REMOVED("MODIFIER_REMOVED"), PACKAGE_ADDED(
			"PACKAGE_ADDED"), PACKAGE_REMOVED("PACKAGE_REMOVED"), PACKAGE_RENAMED(
			"PACKAGE_RENAMED"), PARAMETER_ADDED("PARAMETER_ADDED"), PARAMETER_NAME_CHANGED(
			"PARAMETER_NAME_CHANGED"), PARAMETER_REMOVED("PARAMETER_REMOVED"), PARAMETER_REORDERED(
			"PARAMETER_REORDERED"), PARAMETER_REORDERED_AND_RENAMED(
			"PARAMETER_REORDERED_AND_RENAMED"), PARAMETER_TYPE_CHANGED(
			"PARAMETER_TYPE_CHANGED"), RETURN_TYPE_CHANGED(
			"RETURN_TYPE_CHANGED"), STATIC_BLOCK_ADDED("STATIC_BLOCK_ADDED"), STATIC_BLOCK_REMOVED(
			"STATIC_BLOCK_REMOVED"), THROWS_ADDED("THROWS_ADDED"), THROWS_REMOVED(
			"THROWS_REMOVED"), THROWS_REORDERED("THROWS_REORDERED"), TYPE_CHANGED_FROM_CLASS_TO_INTERFACE(
			"TYPE_CHANGED_FROM_CLASS_TO_INTERFACE"), TYPE_CHANGED_FROM_INTERFACE_TO_CLASS(
			"TYPE_CHANGED_FROM_INTERFACE_TO_CLASS"), TYPE_DECLARATION_ADDED(
			"TYPE_DECLARATION_ADDED"), TYPE_DECLARATION_REMOVED(
			"TYPE_DECLARATION_REMOVED"), VARIABLE_ADDED("VARIABLE_ADDED"), VARIABLE_CHANGED(
			"VARIABLE_CHANGED"), VARIABLE_REMOVED("VARIABLE_REMOVED"), VARIABLE_TYPE_CHANGED(
			"VARIABLE_TYPE_CHANGED");

	private final String str;

	ChangeType(String str) {
		this.str = str;
	}

	public String toString() {
		return str;
	}
}
